Repository andela/team-odd-bn-backend, pull requests merged in 2019-11, with the labels that each got.

#1 #169258620 Integrate HoundCI with badge attached to readme
  .hound.yml
  README.md
Labels: Done, feedback given

#3 #169258617 config postgres database engine
  .env.example
  .gitignore
  package-lock.json
  package.json
Labels: feedback given, feedback implemented

#5 #169258621 Integrate Travis CI with readme badge
  .travis.yml
  README.md
  package-lock.json
  package.json
  src/tests/sample.test.js
Labels: feedback implemented

#7 #169258625 Setup API documentation using swagger
  package-lock.json
  package.json
  src/database/models/user.js
  src/routes/api/users.js
  src/routes/index.js
  src/utils/swaggerOptions.js
Labels: feedback implemented

#19 #169258621 User Registration
  .DS_Store
  package-lock.json
  package.json
  src/.DS_Store
  src/controllers/UserController.js
  src/database/config/config.js
  src/database/migrations/20191113210532-create-users.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/models/users.js
  src/helpers/AuthenticateToken.js
  src/helpers/Customize.js
  src/helpers/HashPassword.js
  src/helpers/index.js
  src/index.js
  src/middlewares/FindUsers.js
  src/middlewares/ValidateUser.js
  src/middlewares/index.js
  src/routes/api/authRoute.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/routes/index.js
  src/tests/mock/mockData.js
  src/tests/test.js
  src/tests/userTest.js
  src/utils/swaggerOptions.js
  src/validation/index.js
Labels: Done

#16 #169258631 user should be able to login
  package-lock.json
  package.json
  src/controllers/UserController.js
  src/database/models/index.js
  src/database/models/users.js
  src/helpers/Customize.js
  src/helpers/HashPassword.js
  src/middlewares/ValidateUser.js
  src/middlewares/validateCredentials.js
  src/routes/api/authRoute.js
  src/tests/index.js
  src/tests/mock/mockData.js
  src/tests/userTest.js
  src/utils/swaggerOptions.js
Labels: Done

#18 #169258629 verification email
  .env.example
  .gitignore
  .hound.yml
  coveralls.yml
  hound.yml
  package-lock.json
  package.json
  src/controllers/UserController.js
  src/database/migrations/20191114111503-create-users.js
  src/database/seeders/20191112155506-demo-user.js
  src/helpers/EmailHelper.js
  src/helpers/EmailTemplates.js
  src/helpers/TokenHelper.js
  src/index.js
  src/routes/api/authRoute.js
  src/routes/index.js
  src/tests/controllers/socialControllers.js
  src/tests/mock/mockData.js
  src/tests/userTest.js
  src/utils/index.js
  src/utils/swaggerOptions.js
Labels: feedback implemented

#20 #169258633 Add reset password feature
  .eslintrc.json
  package-lock.json
  package.json
  src/config/index.js
  src/config/passport.js
  src/controllers/UserController.js
  src/database/migrations/20191114111503-create-users.js
  src/database/migrations/20191115074903-create-users.js
  src/database/models/index.js
  src/database/models/users.js
  src/database/seeders/20191114145912-users.js
  src/helpers/AuthToken.js
  src/helpers/Customize.js
  src/helpers/EmailTemplates.js
  src/helpers/HashedPassword.js
  src/helpers/PasswordHelper.js
  src/helpers/resetPasswordEmail.js
  src/middlewares/ForgotPasswordMiddlewares.js
  src/routes/api/authRoute.js
  src/services/UserService.js
  src/tests/mock/mockData.js
  src/tests/resetPasswordTest.js
  src/tests/userTest.js
Labels: feedback implemented

#21 #169258636 Create a request for one way trip
  .DS_Store
  package.json
  src/.DS_Store
  src/controllers/TripController.js
  src/controllers/UserController.js
  src/database/config/config.js
  src/database/migrations/20191119085945-create-users.js
  src/database/migrations/20191119090000-create-trip-type.js
  src/database/migrations/20191119090013-create-cities.js
  src/database/migrations/20191119104631-create-trip-request.js
  src/database/migrations/20191119104640-create-trip-request-cities.js
  src/database/models/cities.js
  src/database/models/index.js
  src/database/models/tripRequestCities.js
  src/database/models/tripRequests.js
  src/database/models/triptype.js
  src/database/models/users.js
  src/database/seeders/20191114145912-users.js
  src/database/seeders/20191115100759-locations-demo.js
  src/database/seeders/20191119110017-tripType.js
  src/helpers/AuthToken.js
  src/helpers/AuthenticateToken.js
  src/helpers/TokenHelper.js
  src/middlewares/ValidateOneWayTrip.js
  src/middlewares/ValidateUser.js
  src/routes/api/authRoute.js
  src/routes/api/index.js
  src/routes/api/tripRoute.js
  src/tests/controllers/socialControllers.js
  src/tests/mock/mockData.js
  src/tests/tripTest.js
  src/tests/userTest.js
  src/utils/swaggerOptions.js
Labels: Done

#28 169842519 Update README file
  README.md
Labels: Done

#23 #169258638 Multi-city trip request
  package-lock.json
  package.json
  src/controllers/LocationController.js
  src/controllers/TripController.js
  src/controllers/UserController.js
  src/database/migrations/20191101073325-create-roles.js
  src/database/migrations/20191118163016-create-users.js
  src/database/migrations/20191118163024-create-cities.js
  src/database/migrations/20191118163043-create-status.js
  src/database/migrations/20191119091422-create-tripRequests.js
  src/database/migrations/20191119162259-create-trips.js
  src/database/models/cities.js
  src/database/models/status.js
  src/database/models/tripRequestCities.js
  src/database/models/tripRequests.js
  src/database/models/tripType.js
  src/database/models/tripTypes.js
  src/database/models/trips.js
  src/database/models/triptype.js
  src/database/models/user.js
  src/database/seeders/20191101073839-roles.js
  src/database/seeders/20191114145912-users.js
  src/database/seeders/20191115043919-super-admin.js
  src/database/seeders/20191118175739-cities.js
  src/database/seeders/20191119101121-tripRequests.js
  src/database/seeders/20191119101130-tripRequestsCities.js
  src/helpers/AuthenticateToken.js
  src/helpers/ControllerHelper.js
  src/helpers/EmailHelper.js
  src/helpers/EmailTemplates.js
  src/helpers/createTripRequest.js
  src/helpers/index.js
  src/middlewares/Conflict.js
  src/middlewares/DataEngine.js
  src/middlewares/Exists.js
  src/middlewares/TripMiddlewares.js
  src/middlewares/Validate.js
  src/middlewares/ValidateOneWayTrip.js
  src/middlewares/ValidateTrip.js
  src/middlewares/isRoledifferent.js
  src/routes/api/authRoute.js
  src/routes/api/index.js
  src/routes/api/locationRoute.js
  src/routes/api/socialRoute.js
  src/routes/api/tripRoute.js
  src/services/TripService.js
  src/tests/000-index.js
  src/tests/010-userTest.js
  src/tests/020-socialControllers.js
  src/tests/030-rolesTest.js
  src/tests/040-locationTest.js
  src/tests/050-returnTripTests.js
  src/tests/060-tripTest.js
  src/tests/070-resetPasswordTest.js
  src/tests/mock/locationMockData.js
  src/tests/mock/mockData.js
  src/tests/mock/tripMockData.js
  src/tests/tripTest.js
  src/utils/swaggerOptions.js
Labels: Done

#29 #169258640: Create a route for getting user requests
  src/controllers/TripController.js
  src/helpers/ControllerHelper.js
  src/middlewares/isManager.js
  src/middlewares/isUserVerified.js
  src/routes/api/authRoute.js
  src/routes/api/tripRoute.js
  src/tests/010-userTest.js
  src/tests/050-returnTripTests.js
  src/tests/060-tripTest.js
  src/tests/mock/mockData.js
Labels: Done

#32 #169258650 User should be able to edit trip request
  src/controllers/TripController.js
  src/controllers/UserController.js
  src/middlewares/Conflict.js
  src/middlewares/Validate.js
  src/middlewares/ValidateTrip.js
  src/middlewares/findUsers.js
  src/routes/api/tripRoute.js
  src/services/CommonQueries.js
  src/services/TripService.js
  src/tests/060-tripTest.js
  src/tests/mock/mockData.js
  src/tests/mock/tripMockData.js
Labels: Ready for review

#30 #169258644 Add user/manager comment on trip request
  README.md
  src/controllers/CommentController.js
  src/database/migrations/20191119162300-create-comments.js
  src/database/models/comments.js
  src/database/seeders/20191115043919-super-admin.js
  src/middlewares/Exists.js
  src/middlewares/Validate.js
  src/middlewares/findUsers.js
  src/routes/api/commentRoute.js
  src/routes/api/index.js
  src/routes/api/socialRoute.js
  src/tests/010-userTest.js
  src/tests/080-commentTest.js
  src/tests/mock/mockData.js
  src/utils/swaggerOptions.js
Labels: feedback implemented
