Repository andela/team-odd-bn-backend, pull requests merged in 2019-12, with the labels that each got.

#34 #169258643 : Avail requests to manager made by his/her direct reports
  src/controllers/TripController.js
  src/database/migrations/20191115165558-create-user-profile.js
  src/database/migrations/20191119091422-create-tripRequests.js
  src/database/models/tripRequests.js
  src/database/models/user.js
  src/database/seeders/20191114145912-users.js
  src/database/seeders/20191114145913-user-profile.js
  src/helpers/ControllerHelper.js
  src/middlewares/Exists.js
  src/middlewares/TripMiddlewares.js
  src/middlewares/Validate.js
  src/middlewares/ValidateTrip.js
  src/middlewares/isRoledifferent.js
  src/routes/api/tripRoute.js
  src/services/TripService.js
  src/tests/010-userTest.js
  src/tests/050-returnTripTests.js
  src/tests/060-tripTest.js
  src/tests/080-commentTest.js
  src/tests/mock/mockData.js
  src/tests/mock/tripMockData.js
Labels: Ready for review

#35 #169258642 Manager Accept Or Reject User Requests
  src/controllers/TripController.js
  src/controllers/UserController.js
  src/database/seeders/20191114145912-users.js
  src/database/seeders/20191114145913-user-profile.js
  src/database/seeders/20191115043919-super-admin.js
  src/middlewares/Validate.js
  src/middlewares/approveOrReject.js
  src/middlewares/findUsers.js
  src/routes/api/tripRoute.js
  src/tests/010-userTest.js
  src/tests/060-tripTest.js
  src/tests/mock/mockData.js
Labels: Done

#33 #170000444 add strong password rules
  src/database/seeders/20191114145912-users.js
  src/middlewares/Validate.js
  src/tests/mock/mockData.js
Labels: Done

#42 #169258661 User can rate an accommodation centre.
  src/.DS_Store
  src/controllers/AccommodationController.js
  src/database/migrations/20191203155338-create-ratings.js
  src/database/migrations/20191206034854-editAccommodationModel.js
  src/database/migrations/20191206085222-editGoogleCoordinatesColumn.js
  src/database/models/accomodations.js
  src/database/models/ratings.js
  src/database/seeders/20191203191136-accommodation.js
  src/middlewares/AccommodationMiddleware.js
  src/middlewares/Exists.js
  src/middlewares/TripMiddlewares.js
  src/middlewares/Validate.js
  src/routes/api/accommodationRoute.js
  src/routes/api/index.js
  src/services/AccommodationService.js
  src/services/TripService.js
  src/tests/060-tripTest.js
  src/tests/accommodationTest.js
  src/tests/mock/accommodationMockData.js
Labels: feedback implemented

#40 #169258659 user can like/dislike a specific accommodation facility
  package-lock.json
  src/controllers/AccommodationController.js
  src/database/migrations/20191203151312-create-accommodations.js
  src/database/migrations/20191203152322-create-likes.js
  src/database/migrations/20191206085222-editGoogleCoordinatesColumn.js
  src/database/models/accommodations.js
  src/database/models/likes.js
  src/database/seeders/20191203204612-accommodations.js
  src/middlewares/Exists.js
  src/middlewares/Validate.js
  src/routes/api/accommodationRoute.js
  src/services/AccommodationService.js
  src/services/CommonQueries.js
  src/tests/090-accommodationTest.js
  src/tests/accommodationTest.js
  src/utils/swaggerOptions.js
Labels: feedback implemented

#43 #169258646 send notification when trip request approved or rejected
  package-lock.json
  package.json
  src/controllers/TripController.js
  src/database/migrations/20191203223954-create-notifications.js
  src/database/models/notifications.js
  src/database/models/tripRequests.js
  src/database/models/user.js
  src/helpers/eventEmitters.js
  src/helpers/socketIo.js
  src/index.js
  src/middlewares/approveOrReject.js
  src/middlewares/findUsers.js
  src/public/index.html
  src/services/NotificationService.js
  src/tests/060-tripTest.js
  src/tests/090-notification.js
Labels: Done

#41 #169258653 Create accommodation
  src/controllers/AccommodationController.js
  src/database/migrations/20191203089312-create-accommodations.js
  src/database/migrations/20191203093414-create-accomodation-images.js
  src/database/models/accommodations.js
  src/database/models/accomodationimages.js
  src/database/models/cities.js
  src/database/models/rooms.js
  src/middlewares/Conflict.js
  src/middlewares/Validate.js
  src/middlewares/customValidator.js
  src/middlewares/isImageUrl.js
  src/routes/api/accommodationRoute.js
  src/routes/api/index.js
  src/routes/api/userRoute.js
  src/services/AccommodationService.js
  src/services/BookingService.js
  src/tests/090-accommodationTest.js
  src/tests/mock/accommodationMockData.js
Labels: Done

#45 #169776372 Fix heroku error
  Procfile
  package.json
  src/index.js
Labels: Ready for review

#46 #170180348 Modify database schema
  src/database/migrations/20191115165559-modify-user-profile.js
  src/database/migrations/20191203089313-modify-accommodations.js
  src/database/migrations/20191203155339-modify-ratings.js
  src/database/migrations/20191203223955-modify-notifications.js
  src/database/models/accommodations.js
  src/services/AccommodationService.js
  src/services/NotificationService.js
Labels: Ready for review

#47 #169258647 User can delete a comment they posted.
  src/controllers/CommentController.js
  src/middlewares/Validate.js
  src/middlewares/findUsers.js
  src/routes/api/commentRoute.js
  src/routes/api/searchRoute.js
  src/services/CommentService.js
  src/services/CommonQueries.js
  src/tests/080-commentTest.js
  src/tests/100-bookingTest.js
  src/tests/mock/BookingsMockData.js
Labels: feedback implemented

#49 #169258662 users should get stats of trips made in the last X timeframe
  src/controllers/TripController.js
  src/helpers/TripHelper.js
  src/middlewares/Validate.js
  src/middlewares/ValidateTrip.js
  src/middlewares/customValidator.js
  src/routes/api/tripRoute.js
  src/services/TripService.js
  src/tests/060-tripTest.js
  src/tests/100-bookingTest.js
  src/tests/mock/BookingsMockData.js
Labels: Done

#50 #169258656 Notification for creating comment and editing trip request
  src/controllers/CommentController.js
  src/controllers/TripController.js
  src/database/migrations/20191210102155-add-notification-accomodation-comment.js
  src/database/models/notifications.js
  src/helpers/notificationConfig.js
  src/helpers/socketIo.js
  src/index.js
  src/public/index.html
  src/services/NotificationService.js
Labels: Done, feedback implemented

#51 #169258639 notifications of new booking and travel request
  src/controllers/BookingController.js
  src/controllers/LocationController.js
  src/controllers/NotificationController.js
  src/database/migrations/20191203092338-accommodations-add-userId.js
  src/database/migrations/20191203223955-add-booking-Id-notification.js
  src/database/models/accommodations.js
  src/database/models/notifications.js
  src/database/models/user.js
  src/database/seeders/20191103164828-roles.js
  src/database/seeders/20191104145912-users.js
  src/database/seeders/20191105144530-accommodations.js
  src/database/seeders/20191203191136-accommodation.js
  src/database/seeders/20191203204612-accommodations.js
  src/helpers/TripHelper.js
  src/helpers/socketIo.js
  src/middlewares/Validate.js
  src/public/index.html
  src/routes/api/index.js
  src/routes/api/locationRoute.js
  src/routes/api/notificationRoute.js
  src/routes/api/tripRoute.js
  src/services/AccommodationService.js
  src/services/LocationService.js
  src/services/NotificationService.js
  src/tests/040-locationTest.js
  src/tests/060-tripTest.js
  src/tests/090-accommodationTest.js
  src/tests/110-notificationTest.js
  src/tests/mock/mockData.js
  src/tests/mock/notificationMockData.js
  src/tests/mock/tripMockData.js
  src/utils/swaggerOptions.js
Labels: Done

#52 #170230517 Display all notification for a specific user
  src/controllers/UserController.js
  src/database/models/notifications.js
  src/routes/api/userRoute.js
  src/services/NotificationService.js
  src/tests/090-notification.js
Labels: Done

#48 #170180280 Manager get all and specific user booking Requests
  src/controllers/BookingController.js
  src/database/migrations/20191209125407-20191203145130-create-booking.js.js
  src/database/models/booking.js
  src/middlewares/AccommodationMiddleware.js
  src/middlewares/Validate.js
  src/middlewares/findUsers.js
  src/routes/api/bookingRoute.js
  src/services/BookingService.js
  src/tests/100-bookingTest.js
  src/tests/mock/BookingsMockData.js
Labels: feedback implemented

#53 #169258648 User can search trip requests by preference
  src/controllers/SearchController.js
  src/middlewares/SearchMiddleware.js
  src/middlewares/validateSearchQueries.js
  src/routes/api/index.js
  src/routes/api/searchRoute.js
  src/services/SearchService.js
  src/services/commonSearchQueries.js
  src/tests/110-searchTest.js
Labels: feedback implemented
